name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew stage

      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploying to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "todo-backend-stojan"
          heroku_email: "stolea@gmail.com"